# Generated by Django 3.1.7 on 2021-03-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20210325_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': True, 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
